version: "3.8"

# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
x-container-base: &container-base
  init: true
  env_file:
      - .env

services:
  WSIbackend:
    <<: *container-base
    image: ${WSI_VIEWER_BACKEND_IMAGE}
    volumes:
      - ./backend/openslide/app:/app/
      - ./images:/app/images
      - ./annotations:/app/annotations

  WSI_frontend_builder:
    <<: *container-base
    image: ${WSI_VIEWER_FRONTEND_IMAGE}
    volumes:
      - ./frontend2:/frontend/app_to_build
      - ./nginx/html:/frontend/app/build
      - ./frontend2/build_nextjs.sh:/build_nextjs.sh
    entrypoint: ["sh", "/build_nextjs.sh"]

  nginx:
    <<: *container-base
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx:/nginx
      - ./nginx/html:/usr/share/nginx/html/
    entrypoint: ["sh", "/nginx/entry.sh"]
