# v1.7
ARG DOCKER_REGISTRY=docker.io
FROM ${DOCKER_REGISTRY}/library/python:3.11.4-slim-bookworm

ARG PIP_INDEX_URL=https://pypi.org/simple

# 设置工作目录
WORKDIR /app

# 复制项目文件到容器中
COPY ./app /app/app
COPY requirements.txt /app/requirements.txt

# 安装依赖
RUN pip install --no-cache-dir --retries 10 --timeout 120 \
    --index-url "${PIP_INDEX_URL}" -r requirements.txt

# 启动命令
CMD ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--bind", "0.0.0.0:4000"]
