# v1.7
FROM python:3.11.4-slim-bookworm

# 设置工作目录
WORKDIR /app

# 复制项目文件到容器中
COPY ./app /app
COPY requirements.txt /app

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 启动命令
CMD ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:4000"]
